-- Revert data-gameplay_variables

BEGIN;

DELETE FROM variable WHERE player_id = 0 AND name IN (
	'SHIP_UPKEEP', 'UPGRADE_PRICE_SCALE', 'SPAWN_MIN_DISTANCE', 'GRACE_TICS', 'HOME_SAFE_RADIUS',
	'LATE_JOIN_STIPEND', 'LATE_JOIN_FUEL', 'PLANET_REGEN_PER_TIC', 'PLANET_REGEN_CAP',
	'PLANET_REGEN_SMALL_BONUS', 'MISSION_CHECK_EVERY');

COMMIT;
